name: test-shopper

services:
  backend:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=local_user
      - POSTGRES_DB=local_db
      - POSTGRES_PASSWORD=local_password
      - DATABASE_URL=postgres://local_user:local_password@db:5432/local_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on: 
      db:
        condition: service_healthy

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file: "./.env"
    ports:
      - "80:80"
    depends_on:
      backend: 
        condition: service_started

  db:
    container_name: database
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=local_user
      - POSTGRES_DB=local_db
      - POSTGRES_PASSWORD=local_password 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d local_db -U local_user -h db",
        ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: